# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'MVC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'AFNetworking', :inhibit_warnings => true
    pod 'Masonry'
    pod 'MBProgressHUD'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'FMDB'
    pod 'IQKeyboardManager'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'ReactiveCocoa','~>2.1.8'
    pod 'Reachability'
    pod 'UICKeyChainStore'
    #pod 'SDVersion', '~>2.4'
    #pod 'FDFullscreenPopGesture'

  # Pods for MVC

end
